export {buyMohito} from './beverages/mohitoAction'
export {buyBubbleTea} from './beverages/bubbleTeaAction'
export {buyCapachino} from './beverages/capachinoAction'
export {buyIceCoffee} from './beverages/iceCoffeeAction'
export {buyLatte} from './beverages/latteAction'
export {buyPinappleMilkShake} from './beverages/pineappleMSAction'
export {buyStrawberryMilkShake} from './beverages/strawberryMSAction'

export {buyBeefBurger} from './buns/beefBurgerAction'
export {buySandwitch} from './buns/sandwitchAction'
export {buyChickenCheeseBurger} from './buns/chickenCheeseBurgerAction'
export {buySubmarine} from './buns/submarineAction'

export {buySpaghetti} from './mainMeals/spaghettiAction'
export {buyMashPotato} from './mainMeals/mashPotatoAction'
export {buyNoodles} from './mainMeals/noodlesAction'
export {buyBiriyani} from './mainMeals/biriyaniAction'