export  const BUY_MOHITO = 'BUY_MOHITO';
export  const BUY_BUBBLE_TEA = 'BUY_BUBBLE_TEA';
export  const BUY_PINAPPLE_MILK_SHAKE = 'BUY_PINAPPLE_MILK_SHAKE';
export  const BUY_CAPACHONO = 'BUY_CAPACHONO';
export  const BUY_CHOCOLATE_MILK_SHAKE = 'BUY_CHOCOLATE_MILK_SHAKE';
export  const BUY_STRAWBERRY_MILK_SHAKE = 'BUY_STRAWBERRY_MILK_SHAKE';
export  const BUY_LATTE = 'BUY_LATTE';
export  const BUY_ICE_COFFEE = 'BUY_ICE_COFFEE';

export const BUY_BEEF_BURGER = ' BUY_BEEF_BURGER';
export const BUY_SANDWITCH = ' BUY_SANDWITCH';
export const BUY_CHICKEN_CHEESE_BURGER = ' BUY_CHICKEN_CHEESE_BURGER';
export const BUY_SUBMARINE = ' BUY_SUBMARINE';

export const BUY_SPAGHETTI = ' BUY_SPAGHETTI';
export const BUY_MASH_POTATO = ' BUY_MASH_POTATO';
export const BUY_NOODLES = ' BUY_NOODLES';
export const BUY_BIRIYANI = ' BUY_BIRIYANI';