export  const BUY_MOHITO = 'BUY_MOHITO';
export  const BUY_BUBBLE_TEA = 'BUY_BUBBLE_TEA';
export  const BUY_PINAPPLE_MILK_SHAKE = 'BUY_PINAPPLE_MILK_SHAKE';
export  const BUY_CAPACHONO = 'BUY_CAPACHONO';
export  const BUY_CHOCOLATE_MILK_SHAKE = 'BUY_CHOCOLATE_MILK_SHAKE';
export  const BUY_STRAWBERRY_MILK_SHAKE = 'BUY_STRAWBERRY_MILK_SHAKE';
export  const BUY_LATTE = 'BUY_LATTE';
export  const BUY_ICE_COFFEE = 'BUY_ICE_COFFEE';